# comments

#Target : dependency
#<TAB>Command

PROJECT_NAME = 3_Implementation
TEST_PROJ_NAME = Test_$(PROJ_NAME)


SRC = main.c\
src\add.c\
src\del.c\
src\edit.c\
src\search.c\
src\read.c\
src\view.c\
src\write.c\

#TEST_SRC = test/test.c \
#unity/unity.c 
#INC_H = inc
#INC_T = unity

INC = inc

$(PROJECT_NAME):$(SRC)
	gcc -I $(INC) $(SRC)  -o main.exe 
	
	
run : $(PROJECT_NAME)
	$(PROJECT_NAME)

#test:
#	gcc -I $(INC_H) -I $(INC_T) $(TEST_SRC) $(SRC) -o $(call FixPath,$(PROJECT_NAME))
#	./$(call FixPath,$(PROJECT_NAME))

#to delete all the exe files	
clean :
	rm -rf *exe
#del /q .exe didnt work